config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  post 'api', to: 'api#index', as: :api
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
end

app/controllers/api_controller.rb
require 'json'

class ApiController < ApplicationController
  def index
    json = JSON.parse request.body.read.html_safe
    results = RpcSql.execute(json)
    render json: results
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_rpcsql.html.erb
<script type="text/javascript">
/**
  Example:
  RpcSql('<%= api_path %>')
    .select('posts.id', 'email', 'title', 'body')
    .from('users')
    .join('posts', 'users.id', '=', 'posts.user_id')
    .orderBy('posts.id desc')
    .post(callbackFn)
**/

  function RpcSql(url) {
    var fn = {}
    var lastCall = ''
    var payload = {
      select: [],
      from: "",
      join: [],
      leftOuterJoin: [],
      fullOuterJoin: [],
      where: [],
      groupBy: "",
      orderBy: []
    }

    fn.select = function(cols) {
      lastCall = 'select'
      var ary = Array.from(arguments)
      payload.select = payload.select.concat(ary)
      return fn
    }

    fn.from = function(table) {
      lastCall = 'from'
      payload.from = table
      return fn
    }

    fn.join = function(table, col1, operator, col2) {
      lastCall = 'join'
      payload.join.push([table, col1, operator, col2])
      return fn
    }

    fn.leftOuterJoin = function(table, col1, operator, col2) {
      lastCall = 'leftOuterJoin'
      payload.leftOuterJoin.push([table, col1, operator, col2])
      return fn
    }

    fn.fullOuterJoin = function(table, col1, operator, col2) {
      lastCall = 'full outer join'
      payload.fullOuterJoin.push([table, col1, operator, col2])
      return fn
    }

    fn.and = function(col1, operator, col2) {
      // `and` is used for join(), leftOuterJoin(), fullOuterJoin(), where()
      // therefore we track `lastCall` to determine
      // where to place it in the data structure

      var ary = ['and', col1, operator, col2]

      if(lastCall === 'join') {
        payload.join.push(ary)
      } else if(lastCall === 'leftOuterJoin') {
        payload.leftOuterJoin.push(ary)
      } else if(lastCall === 'fullOuterJoin') {
        payload.fullOuterJoin.push(ary)
      } else if(lastCall === 'where') {
        payload.where.push(ary)
      }

      return fn
    }

    fn.where = function(col1, operator, col2) {
      lastCall = 'where'
      var ary = [col1, operator, col2]
      payload.where.push(ary)
      return fn
    }

    fn.groupBy = function(col) {
      lastCall = 'groupBy'
      payload.groupBy = col
      return fn
    }

    fn.orderBy = function(cols, direction) {
      lastCall = 'orderBy'
      var ary = [cols, direction]
      payload.orderBy = ary
      return fn
    }

    fn.overwrite = function(newPayload) {
      lastCall = ''
      payload = newPayload
      return fn
    }

    fn.post = function(successFn) {
      console.log('posting', payload)
      var postData = JSON.stringify(payload)
      $.post(url, postData, function(data) {
        successFn(data)
      }, 'json')
    }

    return fn;
  }
</script>

app/views/home/index.html.erb
<%= render '/home/rpcsql' %>

<style media="screen">
  body, input, textarea, button {
    font-size: 12pt;
  }
</style>

<div>
  <h1>RPC JSON</h1>
  <h2>JavaScript</h2>
<pre>
RpcSql('<%= api_path %>')
  .select('posts.id', 'email as author', 'title', 'body')
  .from('users')
  .join('posts', 'users.id', '=', 'posts.user_id')
  .orderBy('posts.id', 'desc')
  .post(callbackFn)
</pre>
<div>
<div>
  <hr>
  <h2>Response</h2>
  <div id="results"></div>
</div>

<script type="text/javascript">
  $(document).ready(function(e) {
    RpcSql('<%= api_path %>')
      .select('posts.id', 'email as author', 'title', 'body')
      .from('users')
      .join('posts', 'users.id', '=', 'posts.user_id')
      .orderBy('posts.id', 'desc')
      .post(function(data) {
        var str = JSON.stringify(data, "", 2)
        $('#results').html('<pre>' + str + '</pre>')
      })

    /*
    RpcSql('<%= api_path %>')
      .select('users.email', 'count(*) as numOfPosts')
      .from('users')
      .join('posts', 'users.id', '=', 'posts.user_id')
      .groupBy('users.id')
      .post(function(data) {
        var str = JSON.stringify(data, "", 2)
        $('#results').html('<pre>' + str + '</pre>')
      })

    RpcSql('<%= api_path %>')
      .select('comments.body', 'users.email as author')
      .from('comments')
      .join('posts', 'comments.post_id', '=', 'posts.id')
      .join('users', 'posts.user_id', '=', 'users.id')
      .where('comments.user_id', '=', '2')
      .and('posts.id', '=', '2')
      .post(function(data) {
        var str = JSON.stringify(data, "", 2)
        $('#results').html('<pre>' + str + '</pre>')
      })
    */
  })
</script>

app/views/home/index_old.html.erb
<style media="screen">
  body, input, textarea, button {
    font-size: 12pt;
  }
</style>

<div>
  <form id="form" action="/api" method="post">
    <h1>RPC JSON</h1>
    <div><textarea id="rpcsql_body" name="rpcsql" rows="16" cols="70"></textarea></div>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <div><button type="submit" name="button">Submit</button></div>
  </form>
</div>
<div>
  <hr>
  <h2>Results</h2>
  <div id="results"></div>
</div>

<script type="text/javascript">
  function postBody(rpcSql) {
    $.post('<%= api_path %>', rpcSql, function(data) {
      var str = JSON.stringify(data, "", 2)
      $('#results').html('<pre>' + str + '</pre>')
    }, 'json')
  }

  $('form').submit(function(e) {
    e.preventDefault()
    var rpcSql = $('#rpcsql_body').val()
    postBody(rpcSql)
  })

  $(document).ready(function() {
    var defaults = {
      select: ['posts.id', 'email', 'title', 'body'],
      from: "users",
      joins: ["join posts on users.id = posts.user_id"],
      where: [],
      groupBy: [],
      orderBy: ['posts.id desc']
    }

    $('#rpcsql_body').val(JSON.stringify(defaults, "", 2))
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rpcsql</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>